apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: tdp-kpack-template
spec:
  healthRule:
    multiMatch:
      healthy:
        matchConditions:
          - status: "True"
            type: BuilderReady
          - status: "True"
            type: Ready
      unhealthy:
        matchConditions:
          - status: "False"
            type: BuilderReady
          - status: "False"
            type: Ready
  imagePath: .status.latestImage
  lifecycle: mutable
  params:
    - default: default
      name: serviceAccount
    - default: default
      name: clusterBuilder
    - name: registry
      default: {}
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:regexp", "regexp")
    #@ load("@ytt:base64", "base64")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     exclusions = ["kapp.k14s.io/app", "kapp.k14s.io/association"]
    #@     for k,v in dict(data.values.workload.metadata.labels).items():
    #@       if k not in exclusions:
    #@         labels[k] = v
    #@       end
    #@     end
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def image():
    #@   return "/".join([
    #@    data.values.params.registry.server,
    #@    data.values.params.registry.repository,
    #@    "-".join([
    #@      data.values.workload.metadata.name,
    #@      data.values.workload.metadata.namespace,
    #@    ])
    #@   ])
    #@ end
    
    #@ bp_node_run_scripts = "set-tpb-config,portal:pack"
    #@ tpb_config = "/tmp/tpb-config.yaml"

    #@ if "env" in data.values.workload.spec.build:
    #@   for env in data.values.workload.spec.build.env:
    #@     if env.name == "TPB_CONFIG_STRING":
    #@       tpb_config_string = env.value
    #@     end
    #@     if env.name == "BP_NODE_RUN_SCRIPTS":
    #@       bp_node_run_scripts = env.value
    #@     end
    #@     if env.name == "TPB_CONFIG":
    #@       tpb_config = env.value
    #@     end
    #@   end
    #@ end
    
    #@ if "params" in data.values.workload.spec:
    #@   for param in data.values.workload.spec.params:
    #@     if param.name == "tpb_plugins":
    #@       tpb_config_string = base64.encode(param.value)
    #@     end
    #@   end
    #@ end
    
    apiVersion: kpack.io/v1alpha2
    kind: Image
    metadata:
      name: #@ data.values.workload.metadata.name
      labels: #@ merge_labels({ "app.kubernetes.io/component": "build" })
    spec:
      tag: #@ image()
      serviceAccountName: #@ data.values.params.serviceAccount
      builder:
        kind: ClusterBuilder
        name: #@ data.values.params.clusterBuilder
      source:
        blob:
          url: #@ data.values.source.url
        subPath: builder
      build:
        env:
        - name: BP_OCI_SOURCE
          value: #@ data.values.source.revision
        #@  if regexp.match("^([a-zA-Z0-9\/_-]+)(\@sha1:)?[0-9a-f]{40}$", data.values.source.revision):
        - name: BP_OCI_REVISION
          value: #@ data.values.source.revision
        #@ end
        - name: BP_NODE_RUN_SCRIPTS
          value: #@ bp_node_run_scripts
        - name: TPB_CONFIG
          value: #@ tpb_config
        - name: TPB_CONFIG_STRING
          value: #@ tpb_config_string
